### ISSUE TITLE
User-provided Detekt CLI Jar

### ISSUE THREAD

**Issue by artem-zinnatullin** [buildfoundation/bazel_rules_detekt#14]
To allow user-specific updates and or forks of Detekt.

This is easy to support as is, but API might change with Persistent Worker support #7 due to potential changes in classloading/etc, thus it's on hold

**Comment by arturdryomov** [comment]
In general adopting a common approach of workspace macros should do the trick but there are interesting details. I’ve explored multiple variants, we’ll need to decide which one to pick.

### `java -cp`

* There is a potential Kotlin runtimes conflict. Since we use the `cli-all` artifact it contains everything, including the Kotlin runtime. Which we include as well since the wrapper is written in Kotlin. The worst part — we’ll know about the issue... in runtime.
* We use reflection right now to access Detekt methods which is not compile-time safe. Performance-wise it not optimal as well.
* A user-defined version will break the worker-related flow. Bazel will not restart a worker on version changes since it is a rule attribute, i. e. from the Bazel perspective inputs have changed and the worker should proceed, just with different inputs. This can be resolved with a classpath sandboxing if it is even possible (without gross hacks).

### `http_file` + `kt_jvm_import`

* The same as `java -cp` but without reflection. The runtimes conflict is still here unfortunately.
* In practice does not work with the IDE plugin — aspects get messed up and the IDE doesn’t see Detekt classes. Bazel compiles fine though, even with Detekt imports and usages in the wrapper source code.
* A user-defined version works fine. Changing the version restarts the worker.

### `rules_jvm_external`

* Restarts the worker on version changes.
* Works with the IDE.
* No reflection.
* No runtimes conflict — in theory. In practice I get this and don’t understand what’s happening (`rules_kotlin` should handle this, right?)

    ```
    warning: some JAR files in the classpath have the Kotlin Runtime library bundled into them. This may cause difficult to debug problems if there's a different version of the Kotlin Runtime library in the classpath. Consider removing these libraries from the classpath
    bazel-out/host/bin/external/maven/v1/https/jcenter.bintray.com/org/jetbrains/kotlin/kotlin-reflect/1.3.61/stamped_kotlin-reflect-1.3.61.jar: warning: library has Kotlin runtime bundled into it
    bazel-out/host/bin/external/maven/v1/https/jcenter.bintray.com/org/jetbrains/kotlin/kotlin-stdlib/1.3.61/stamped_kotlin-stdlib-1.3.61.jar: warning: library has Kotlin runtime bundled into it
    ``` 

---

Seems like `rules_jvm_external` is a win, especially if we manage to resolve the warning. @artem-zinnatullin, do you have extra concerns?

**Comment by arturdryomov** [comment]
Let’s continue in #35.
