### ISSUE TITLE
Add plugins options

### ISSUE THREAD

**Issue by scorsi** [buildfoundation/bazel_rules_detekt#75]
Hello 👋 

Issue related to #74.

I'm looking to deal with Detekt formatting. While looking [here](https://detekt.github.io/detekt/formatting.html) it appear we need to add a Gradle task or passing the `io.gitlab.arturbosch.detekt:detekt-formatting` jar into the `plugins` parameter while invoking Detekt.

While looking [here](https://github.com/buildfoundation/bazel_rules_detekt/blob/master/docs/rule.md) it looks like this project doesn't support passing `plugins` options.

I'll keeping investigation and may create a PR with the additional feature and doc to add Ktlint formatting. But I don't have the workload actually.

Thanks,

**Comment by arturdryomov** [comment]
@Kernald, do you have ideas how it can be done? I’ve looked into it and cannot think of a workaround.

Using `rules_jvm_external`:

* Seems like it’s enough to supply additional rules on a classpath. In an ideal world scenario such rules should be additional dependencies of [the `lib` target](https://github.com/buildfoundation/bazel_rules_detekt/blob/5a6b0e2779ce0390a189882206a3191561925758/detekt/wrapper/BUILD#L15).
* [We can do that](https://github.com/bazelbuild/rules_jvm_external#exporting-and-consuming-artifacts-from-external-repositories) for declaring extra dependencies on the `maven_install` stage via passing a dependencies list in the `rules_detekt_toolchains` macro. 
* Unfortunately, I have no idea how to use resulting labels in the wrapper `BUILD` file above. A weird idea I had is to make custom labels using a prefix like `detekt_rules_X` and using `deps = glob(["detekt_rules_*"])` in the `BUILD` file but it doesn’t seem to work (even using `glob` on existing dependencies doesn’t). I guess because `deps` should be targets, not arbitrary strings.

Using Detekt CLI:

* The Detekt CLI has [a `--plugins` option](https://arturbosch.github.io/detekt/cli.html). Such plugins (read rulesets) are desirable to have [as a single JAR](https://detekt.github.io/detekt/extensions.html#let-detekt-know-about-your-extensions) (this is a bit optimistic though).
* It would be nice to pass rules artifacts in the `rules_detekt_toolchains` macro, declare them via `rules_jvm_external` and resolve JAR paths on the rule level. But I cannot find a macro that can help with this.

**Comment by Kernald** [comment]
I see a relatively easy way (at least in my mind, I might be missing something obvious) to do it at the `detekt()` rule level (have an optional label list, making `JavaInfo` mandatory for those, and pass their path to `--plugins` - if needed, I guess you could even declare a private `java_library` exporting all of them to have a single `--plugins` entry), but I'm really not familiar with toolchains, and I don't see any obvious solution there, sorry...

**Comment by arturdryomov** [comment]
@Kernald, thanks! I guess it sounds kind of like the second approach. But the unknown piece of the puzzle is to resolve JAR paths from either `JavaInfo` or plain labels...

**Comment by Kernald** [comment]
Ha sorry, I assumed this part was easy, but I haven't actually checked how to do it :-p Looks like [this](https://docs.bazel.build/versions/master/skylark/lib/JavaInfo.html#outputs) should contain the path to the jar? It's not clear what type [this](https://docs.bazel.build/versions/master/skylark/lib/java_output_jars.html#jars) list is...

**Comment by arturdryomov** [comment]
Huh, seems like you are correct, thanks again! Now I need to find some rules accepting `JavaInfo` and steal their approaches 👻
